steps:
  - name: 'seanmorris/build-env'
    args: ['touch', '.env']
  - name: 'seanmorris/build-env'
    args: ['make', 'dependencies']
    env:
      - STAGE_ENV=production
      - EXTERNAL_IP=34.74.220.149
  - name: 'seanmorris/build-env'
    args: ['make', 'build']
    env:
      - STAGE_ENV=production
      - EXTERNAL_IP=34.74.220.149
  - name: 'seanmorris/build-env'
    args: ['make', 'push-images']
    env:
      - STAGE_ENV=production
      - EXTERNAL_IP=34.74.220.149
  - name: 'seanmorris/build-env'
    args: ['make', 'cluster-apply']
    env:
      - STAGE_ENV=production
      - EXTERNAL_IP=34.74.220.149
