version: '3'

services:
  # thruput.isotope.seanmorr.is:
  #   image: thruput.isotope.seanmorr.is
  #   restart: always
  #   ports:
  #     - "9999:80"
  #   depends_on:
  #     - isotope.seanmorr.is
  #     - backend.isotope.seanmorr.is

  # isotope.seanmorr.is:
  #   image: isotope.seanmorr.is
  #   restart: always
  #   ports:
  #     - "9998:80"

  backend.isotope.seanmorr.is:
    build:
      context: ../
      dockerfile: infra/backend.Dockerfile
    image: r.cfcr.io/seanmorris/backend.isotope.seanmorr.is
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../:/app
    depends_on:
      - database.isotope.seanmorr.is

  worker.isotope.seanmorr.is:
    build:
      context: ../
      dockerfile: infra/worker.Dockerfile
    image: r.cfcr.io/seanmorris/worker.isotope.seanmorr.is
    restart: on-failure
    volumes:
      - ../:/app
    depends_on:
      - database.isotope.seanmorr.is

  updater.isotope.seanmorr.is:
    build:
      context: ../
      dockerfile: infra/updater.Dockerfile
    image: r.cfcr.io/seanmorris/updater.isotope.seanmorr.is
    restart: on-failure
    volumes:
      - ../:/app
    depends_on:
      - database.isotope.seanmorr.is

  database.isotope.seanmorr.is:
    image: mysql:5.7
    restart: always
    ports:
      - "9996:3306"
    volumes:
      - schema.isotope.seanmorr.is:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'supersecret'
      MYSQL_USER: 'isotope'
      MYSQL_PASSWORD: 'iso_secret'
      MYSQL_DATABASE: 'isotope'
    command: ['mysqld', '--character-set-server=utf8mb4']

  socket.isotope.seanmorr.is:
    build:
      context: ../
      dockerfile: vendor/seanmorris/subspace/infra/socket.Dockerfile
    image: r.cfcr.io/seanmorris/socket.isotope.seanmorr.is
    restart: always
    ports:
      - "9998:9998"
    volumes:
      - ../:/app
    depends_on:
      - database.isotope.seanmorr.is

  # jenkins:
  #   image: r.cfcr.io/seanmorris/seanmorris/isotope-jenkins:master
  #   restart: always
  #   ports:
  #     - "9995:8080"
  #   volumes:
  #     - jenkins:/var/jenkins_home

  compose.isotope.seanmorr.is:
    build:
      context: ../
      dockerfile: infra/compose.Dockerfile
    image: r.cfcr.io/seanmorris/compose.isotope.seanmorr.is
    restart: on-failure
    volumes:
      - ../:/app
      - ../data/local/composer/:/root/.composer/

volumes:
  schema.isotope.seanmorr.is:
    driver: "local"
