apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: load-balancer
  annotations:
spec:
 rules:
 - host: isotope.$HOST
   http:
     paths:
     - backend:
         serviceName: backend
         servicePort: 80
