apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  selector:
    matchLabels:
      app: database
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: database
        role: master
        tier: backend
    spec:
      containers:
        - name: database
          image:  mariadb:10.4.8-bionic
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: supersecret
            - name: MYSQL_USER
              value: isotope
            - name: MYSQL_PASSWORD
              value: iso_secret
            - name: MYSQL_DATABASE
              value: isotope
            # - name: GET_HOSTS_FROM
            #   value: dns
            # - name: GET_HOSTS_FROM
            #   value: dns
      #     volumeMounts:
      #       - name: mysql-volume
      #         mountPath: /var/lib/mysql
      # volumes:
      #   - name: mysql-volume
      #     persistentVolumeClaim:
      #       claimName: mysql-volume-claim
