apiVersion: v1
kind: Service
metadata:
  name: socket
  labels:
    app: socket
    tier: frontend
spec:
  type: LoadBalancer 
  ports:
    - port:       80
      targetPort: 80
      protocol:   TCP
  selector:
    app: socket
    tier: frontend
