version: '2.4'

services:

  backend:
    build:
      target: production
    extends:
      file: docker-compose.base.yml
      service: backend
    ports:
      - "8088:80"
    volumes:
      - /tmp:/tmp
    depends_on:
      - database

  frontend:
    extends:
      file: docker-compose.base.yml
      service: frontend
    ports:
      - "8008:80"
    depends_on:
      - database
      - backend

  cache-warmer:
    extends:
      file: docker-compose.base.yml
      service: cache-warmer
    depends_on:
      - rabbit

  load-balancer:
    extends:
      file: docker-compose.base.yml
      service: load-balancer
    ports:
      - "80:80"
    volumes:
      - ../../data/global/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - database
      - backend
      - frontend

  updater:
    build:
      target: production
    extends:
      file: docker-compose.base.yml
      service: updater
    restart: on-failure
    depends_on:
      - database
    command: ['idilic', 'applySchemas', '1']

  socket:
    build:
      target: production
    extends:
      file: docker-compose.base.yml
      service: socket
    ports:
      - '9998:9998'
    depends_on:
      - database

  database:
    extends:
      file: docker-compose.base.yml
      service: database
    volumes:
      - schema:/var/lib/mysql

  rabbit:
    extends:
      file: docker-compose.base.yml
      service: rabbit

volumes:
  schema:
    driver: 'local'
