version: '2.4'

services:

  backend:
    build:
      target: development
    extends:
      file: docker-compose.base.yml
      service: backend
    ports:
      - "8088:80"
    volumes:
      - ../../:/app
      - /tmp:/tmp
    depends_on:
      - database

  frontend:
    extends:
      file: docker-compose.base.yml
      service: frontend
    ports:
      - "8008:80"
    depends_on:
      - database
      - backend

  cache-warmer:
    extends:
      file: docker-compose.base.yml
      service: cache-warmer
    depends_on:
      - rabbit

  load-balancer:
    extends:
      file: docker-compose.base.yml
      service: load-balancer
    ports:
      - "80:80"
    volumes:
      - ../../data/global/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - database
      - backend
      - frontend

  socket:
    build:
      target: development
    extends:
      file: docker-compose.base.yml
      service: socket
    ports:
      - '9998:9998'
    volumes:
      - ../../:/app
    depends_on:
      - database

  watcher:
    build:
      target: development
    extends:
      file: docker-compose.base.yml
      service: watcher

  updater:
    build:
      target: development
    extends:
      file: docker-compose.base.yml
      service: updater
    restart: on-failure
    volumes:
      - ../../:/app
    depends_on:
      - database

  database:
    extends:
      file: docker-compose.base.yml
      service: database

  rabbit:
     extends:
      file: docker-compose.base.yml
      service: rabbit
    volumes:
      - ../../data/global/rabbitMq/enabled_plugins:/etc/rabbitmq/enabled_plugins

  redis:
     extends:
      file: docker-compose.base.yml
      service: redis

volumes:
  schema.isotope.seanmorr.is:
    driver: 'local'

  # worker:
  #   build:
  #     target: development
  #   extends:
  #     file: docker-compose.base.yml
  #     service: worker
  #   volumes:
  #     - ../../:/app
  #   depends_on:
  #     - database
